export PLAN_SERVICE="${APPLICATION_NAME}-${ENVIRONMENT_NAME}-plan-service"
export RESOURCE_GROUP="${APPLICATION_NAME}-${ENVIRONMENT_NAME}-resource-group"
export DB_SERVER="${APPLICATION_NAME}-${ENVIRONMENT_NAME}-sqlserver"
export BLOB_AZURE_ACCOUNT_NAME="${APPLICATION_NAME}${ENVIRONMENT_NAME}"

export SSO="sso"
export SSO_WEB_APP="${APPLICATION_NAME}-${ENVIRONMENT_NAME}-${SSO}-webapp"

export ONBOARDING="onboarding"
export ONBOARDING_WEB_APP="${APPLICATION_NAME}-${ENVIRONMENT_NAME}-${ONBOARDING}-webapp"

export UPLOAD="upload"
export UPLOAD_WEB_APP="${APPLICATION_NAME}-${ENVIRONMENT_NAME}-${UPLOAD}-webapp"

