INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),getdate(), 'Brasil', 0)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),getdate(),'Argentina', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Afeganistão', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'África do Sul', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Akrotiri', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Albânia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Alemanha', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Andorra', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Angola', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Anguila', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Antárctida', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Antígua e Barbuda', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Arábia Saudita', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Arctic Ocean', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Argélia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Arménia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Aruba', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Ashmore and Cartier Islands', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Atlantic Ocean', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Austrália', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Áustria', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Azerbaijão', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Baamas', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Bangladeche', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Barbados', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Barém', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Bélgica', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Belize', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Benim', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Bermudas', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Bielorrússia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Birmânia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Bolívia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Bósnia e Herzegovina', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Botsuana', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Brunei', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Bulgária', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Burquina Faso', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Burúndi', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Butão', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Cabo Verde', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Camarões', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Camboja', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Canadá', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Catar', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Cazaquistão', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Chade', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Chile', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'China', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Chipre', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Clipperton Island', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Colômbia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Comores', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Congo-Brazzaville', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Congo-Kinshasa', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Coral Sea Islands', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Coreia do Norte', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Coreia do Sul', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Costa do Marfim', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Costa Rica', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Croácia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Cuba', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Curacao', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Dhekelia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Dinamarca', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Domínica', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Egipto', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Emiratos Árabes Unidos', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Equador', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Eritreia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Eslováquia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Eslovénia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Espanha', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Estados Unidos', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Estónia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Etiópia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Faroé', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Fiji', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Filipinas', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Finlândia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'França', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Gabão', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Gâmbia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Gana', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Gaza Strip', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Geórgia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Geórgia do Sul e Sandwich do Sul', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Gibraltar', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Granada', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Grécia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Gronelândia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Guame', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Guatemala', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Guernsey', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Guiana', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Guiné', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Guiné Equatorial', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Guiné-Bissau', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Haiti', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Honduras', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Hong Kong', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Hungria', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Iémen', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Ilha Bouvet', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Ilha do Natal', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Ilha Norfolk', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Ilhas Caimão', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Ilhas Cook', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Ilhas dos Cocos', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Ilhas Falkland', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Ilhas Heard e McDonald', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Ilhas Marshall', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Ilhas Salomão', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Ilhas Turcas e Caicos', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Ilhas Virgens Americanas', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Ilhas Virgens Britânicas', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Índia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Indian Ocean', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Indonésia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Irão', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Iraque', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Irlanda', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Islândia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Israel', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Itália', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Jamaica', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Jan Mayen', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Japão', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Jersey', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Jibuti', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Jordânia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Kosovo', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Kuwait', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Laos', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Lesoto', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Letónia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Líbano', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Libéria', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Líbia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Listenstaine', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Lituânia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Luxemburgo', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Macau', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Macedónia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Madagáscar', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Malásia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Malávi', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Maldivas', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Mali', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Malta', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Man, Isle of', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Marianas do Norte', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Marrocos', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Maurícia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Mauritânia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'México', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Micronésia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Moçambique', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Moldávia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Mónaco', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Mongólia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Monserrate', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Montenegro', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Mundo', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Namíbia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Nauru', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Navassa Island', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Nepal', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Nicarágua', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Níger', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Nigéria', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Niue', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Noruega', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Nova Caledónia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Nova Zelândia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Omã', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Pacific Ocean', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Países Baixos', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Palau', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Panamá', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Papua-Nova Guiné', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Paquistão', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Paracel Islands', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Paraguai', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Peru', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Pitcairn', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Polinésia Francesa', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Polónia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Porto Rico', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Portugal', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Quénia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Quirguizistão', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Quiribáti', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Reino Unido', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'República Centro-Africana', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'República Checa', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'República Dominicana', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Roménia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Ruanda', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Rússia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Salvador', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Samoa', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Samoa Americana', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Santa Helena', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Santa Lúcia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'São Bartolomeu', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'São Cristóvão e Neves', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'São Marinho', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'São Martinho', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'São Pedro e Miquelon', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'São Tomé e Príncipe', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'São Vicente e Granadinas', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Sara Ocidental', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Seicheles', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Senegal', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Serra Leoa', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Sérvia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Singapura', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Sint Maarten', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Síria', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Somália', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Southern Ocean', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Spratly Islands', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Sri Lanca', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Suazilândia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Sudão', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Sudão do Sul', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Suécia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Suíça', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Suriname', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Svalbard e Jan Mayen', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Tailândia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Taiwan', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Tajiquistão', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Tanzânia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Território Britânico do Oceano Índico', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Territórios Austrais Franceses', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Timor Leste', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Togo', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Tokelau', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Tonga', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Trindade e Tobago', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Tunísia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Turquemenistão', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Turquia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Tuvalu', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Ucrânia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Uganda', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'União Europeia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Uruguai', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Usbequistão', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Vanuatu', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Vaticano', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Venezuela', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Vietname', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Wake Island', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Wallis e Futuna', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'West Bank', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Zâmbia', 1)
INSERT INTO Countries (CreatedAt, Name, CheckForeignGraduation) VALUES (getdate(),'Zimbabué', 1)